### PR TITLE
:art:  Shlu/feature/leaderboard interface

### PR DESCRIPTION
**Pull request by shuyenla**
leaderboard interface !
left to do:
 link rank and winrate
 link user profile
 link photo

The level for now is fake data i put directly to the front. It's for demo it for this moment!

### CODE REVIEW

**Comment by fcavillo** [comment]
Hey, the leaderboard is empty for me when I log in with 42?

It works (and looks great) with the accounts on the local login !

**Comment by shuyenla** [comment]
> Hey, the leaderboard is empty for me when I log in with 42?
> 
> It works (and looks great) with the accounts on the local login !

okay!! i'm going to add the line to fetch leaderboard info to front after Lou merge the update
so this will be fixed after :smile_cat: 
thanks for the check i did even notice it doesn't word :rofl: :

**Review by mvaldes42 — APPROVED** [review]
Looks great :100: 
Yep agree with flo, but we'll fix this after :)

**Review by fcavillo — APPROVED** [review]
Nice design !!

**Pull request merged**
