### PR TITLE
Flo/feature/game data

### PR DESCRIPTION
**Pull request by fcavillo**
Game data main update 🥅

- a Game is now an entity, created each game, with the data  in it
- Users have a winRate, a playTime, a score and a rank
- scores are calculated following an ELO ranking system, where the score bonus or malus you get depends on the opponent's rank
- ranks in each users are updated at the end of every game
- Users have a gameHistory that returns subjectiveGameDtos, where info is given based on the current user

### CODE REVIEW

**Review by 5atchm1n — APPROVED** [review]
Nickel, I approve !!

**Comment by shuyenla** [comment]
Seems like working well! just haven't merge with the main branch yet
Also I could not control the pedal of  the game for the moment, but i assume it's not your issue right ?

**Review by shuyenla — APPROVED** [review]

**Comment by shuyenla** [comment]
maybe there would be unresolved conflict after merge so maybe it's better to merge main the this branch before merge it to main directly ;)

**Comment by shuyenla** [comment]
Oh it's myside issue  no problem with the merge !

**Pull request merged**
