### PR TITLE
Satch/auth/field validation

### PR DESCRIPTION
**Pull request by 5atchm1n**
Added default avatar
Added signup field validators

### CODE REVIEW

**Comment by 5atchm1n** [comment]
Can I force merge as well ?

**Comment by 5atchm1n** [comment]
Read the commits, you need to add a var to the env file.

**Comment by mvaldes42** [comment]
> Read the commits, you need to add a var to the env file.

yes, it was hidden :)

**Comment by 5atchm1n** [comment]
The max is just there to stop people from sending us a copy of Hamlet in the post request.

**Comment by mvaldes42** [comment]
> 1. we need server side validation for when we change username and email in the private profile as well



> The max is just there to stop people from sending us a copy of Hamlet in the post request.

ok

**Comment by 5atchm1n** [comment]
This is in Flos code and I will make another PR. Can you approve this so we get the avatar stuff please ?

**Comment by mvaldes42** [comment]
Sure :)

**Review by mvaldes42 — APPROVED** [review]
Default avatar and serveur side validation for signup 👌

**Pull request merged**
