### PR TITLE
Satch/upload/avatars

### PR DESCRIPTION
**Pull request by 5atchm1n**
:rocket: file upload ready (using Multer)
:warning: please update your .env and .prod.env file
:heavy_plus_sign: new volume in docker for uploads

POST -> /upload/avatar (upload file in multipart from)
GET -> /upload/avatar (return current user avatar)
POST -> /upload/getavatar (pass userId<string> return avatar of given user)

### CODE REVIEW

**Review by fcavillo — CHANGES_REQUESTED** [review]
The 3 routes work well, there is a size limit, files are well attributed and getable from the users.
This is just a comment despite my approval, for 2 reasons : 
- Small conflicts with main before merging
- One small remark : the post/getavatar takes _otherId: string_ as a param, ids are ints in the project, so we could change the :string by a :number or :int to keep a general consensus on how to use the ids ?
Great job anyway @5atchm1n :1st_place_medal:

**Review by fcavillo — APPROVED** [review]

**Review by mvaldes42 — APPROVED** [review]
:+1:

**Review by mvaldes42 — CHANGES_REQUESTED** [review]
.

**Review by mvaldes42 — APPROVED** [review]

**Review by shuyenla — APPROVED** [review]
works! cool! good job @5atchm1n :+1:

**Pull request merged**
