### PR TITLE
🚀 Shlu/feature/complete chat

### PR DESCRIPTION
**Pull request by shuyenla**
yay chat is done! now we need some hard tests 🎉

to test:
  0. clear the database if it was built already, cause the schema is updated!
1. sign up several accounts so you can talk to yourself
    > before your sign up any users, if your browser is still in logged in status there will be error it's normal
2. create different types of chat (public/private/protected with password)
3. assign users as admin/take back admin right/change the channel setting, if you're owner
4. kick out/mute users, if you're admin
5. invite users to channel, if you're at least a member
6. search for user to DM/public chat/my chat
7. user will be able to see private channel only if they are invited, 
    if the channel is protected by password user still need to be checked by password
8. join/leave/block channels
9. send/unsend msgs
10. log out and back in to see if data is correct

some must do rely on other parts that we'll deal with it later:
1. display online status
2. fetch searching suggestion to all the users while new user sign up 
3. add friend/block user
4. invite to a game
5. link to user profile
6. display avatar
... and more i haven't think about ...

those we maybe can do:
1. last msg sent time in preview
2. msgs sent time in chatroom
3. edit msg
4. unread count show up on preview

hope you like it 🥰

### CODE REVIEW

**Comment by shuyenla** [comment]
there're a lot of commits cause i rebased... it's only 1/2 actually

**Comment by mvaldes42** [comment]
- [ ] create different types of chat (public/private/protected with password)
- [ ] assign users as admin/take back admin right/change the channel setting, if you're owner
- [ ] kick out/mute users, if you're admin
- [ ] invite users to channel, if you're at least a member
- [ ] search for user to DM/public chat/my chat
- [ ] user will be able to see private channel only if they are invited,
- [ ] if the channel is protected by password user still need to be checked by password
- [ ] join/leave/block channels
- [ ] send/unsend msgs
- [ ] log out and back in to see if data is correct


- is there a way to unblock channels ? Like a list of blocked channels
- perhaps unmute option 
- sometimes right click doesnt work on users, sometimes it doubles
- don't know if emoji windows is open all the time by design ?
- if the channel is protected by password, and we invite a user, no password is asked ?

**Comment by mvaldes42** [comment]
> * sometimes right click doesnt work on users, sometimes it doubles

Screenshot from 2022-08-01 11-53-29

**Comment by shuyenla** [comment]
> > * sometimes right click doesnt work on users, sometimes it doubles
> 
> 
> 
> Screenshot from 2022-08-01 11-53-29
> 
> 

Oh that's interesting, let me take a look

**Comment by mvaldes42** [comment]
for the fac that sometimes right click doesnt work might have something to do with the clickable area ? perhaps it's too thin ? too small ?

**Comment by shuyenla** [comment]
> All above works well ! :clap: 
> 
> 
> 
> A few questions:
> 
> - is there a way to unblock channels ? Like a list of blocked channels

There's no for now, but for sure I can do it if you want
> - perhaps unmute option 
Okay 
> - sometimes right click doesnt work on users, sometimes it doubles
Which specific button doesn't work do you remember? 
> - don't know if emoji windows is open, when we open a channel by design ?
This must be a mistake I didn't notice
> - if the channel is protected by password, and we invite a user, no password is asked ?
Yes the passwords asked if it's not it's an error
> - seems like perhaps the CSS was changed, and it affected the rest of the front
Do you mean I put the chat to full size?

**Comment by mvaldes42** [comment]
> Which specific button doesn't work do you remember?
On the right side, for users that are in the channel, the clickable area doesn't seem to work all the time.

> Yes the password's asked if it's not it's an error
So I did a password protected channel, invited one user. Then logged in with said user, went to the channel and no password was asked.

> Do you mean I put the chat to full size?
This can be adjusted later, but I was talking about the colours of the front in user profile, they were not white before. So maybe we used the same CSS element and modified it ?

**Comment by shuyenla** [comment]
For the add friend and block user and invite to a game, we need to wait to cooperate with user service, they are not working if the background is grey, bbut if you're a paner you'll see extra buttons that's working!

**Comment by shuyenla** [comment]
> > Yes the password's asked if it's not it's an error
> 
> >
> 
> So I did a password protected channel, invited one user. Then logged in with said user, went to the channel and no password was asked. Don't know if I was supposed to test like this ?

Sure! It's a stuff I need to take a look too then. Cause it should still be checked with password
> 
> > Do you mean I put the chat to full size?
> 
> >
> 
> This can be adjusted later, but I was talking about the colours of the front in user profile, they were not white before. So maybe we used the same CSS element and modified it ?
> 
Is it the placeholder issue? Otherwise I don't know why it would effect your part cause I didn't use or touch your css 😢

**Comment by mvaldes42** [comment]
Ok ! should we approve pull request then or wait for more commits ?

> Is it the placeholder issue? Otherwise I don't know why it would effect your part cause I didn't use or touch your css 😢

It's ok then, i'll have a look when i come back 😄

**Comment by shuyenla** [comment]
I can create a branch to fix the issues if merge is urgent, otherwise I'll fix those on this branch. Excuse me for the delay, I was on my way back to Paris yesterday
I'll work on these feedbacks today 😊

**Review by 5atchm1n — COMMENTED** [review]
Hey Shuyen,
Looks like you and Lou are dealing with the front end bugs. I'll wait a little before I approve the merge, on the backend side things seem to be good, I will take another look today but at first glance its great !!

**Comment by shuyenla** [comment]
> So I did a password protected channel, invited one user. Then logged in with said user, went to the channel and no password was asked. Don't know if I was supposed to test like this ?

for this case, if you add the members in the create new room card, they won't be checked by password cause it's operate by owner. only if user is invited after the channel is created, password will be asked.

i mention this because i can not reproduce the unchecked password behavior

**Comment by shuyenla** [comment]
@ft-transcendence/best-team for the unblock and unmute, i feel like they would fit in the maybe can do list, I would like to move on to the leaderboard interface for the moment if you don't mind

**Comment by shuyenla** [comment]
to summarize,
issue reported by @mvaldes42 as following:

- [ ] unblock channel
> list to maybe-do-list 
- [ ] unmute user
> list to maybe-do-list 
- [x] right click multiplied issue
- [x] emoji issue
- [?] channel protected with invitation issue
- [?] CSS issue

**Comment by mvaldes42** [comment]
@shuyenla
- password not check was indeed when added in the create channel, so it's ok then :)
- css issue, i'll deal with it later

So i'ts a go for me 🥳

**Review by mvaldes42 — APPROVED** [review]

**Review by 5atchm1n — APPROVED** [review]
Let's go @shuyenla !!

**Pull request merged**
