### PR TITLE
Flo/fix/status conflicts

### PR DESCRIPTION
**Pull request by mvaldes42**
- Changes in the back done by @fcavillo 
- Changes in the front done by @mvaldes42 

1. displays online statuses of users in the private profile for now, in friends/pending/blocked list
2. it listens to a socket, and uses a react context that can be accessed anywhere in the app using `const usersStatus = useContext(UsersStatusCxt);` and then

```
if (usersStatus) {
  found = usersStatus.find(
    (x: IUserStatus) => x.key === _IdOfUser_
  );
  if (found) _status_ = found.userModel.status;
}
``` 
This way, you can find back the user's status you want to display.

3. Divided `App.css` in several files for lisibility.
4. I'll add statuses to public profile when the other pull request #54  is approved.

### CODE REVIEW

**Review by fcavillo — APPROVED** [review]
Status work : offline, online, ingame. Thanks @mvaldes42 for all your fixes :+1: 

Small socket  tweak to make around the game exiting, but an ulterior push can solve this.

**Comment by 5atchm1n** [comment]
We are going to have to use namespacea for the sockets, which we should have been doing from the start. It also for multiplexing and allows the nginx proxy to work. Basically the chat and game have their own namespace, which allows for SOC (seperation of concerns) is this going to affect your stuff @fcavillo ?

**Comment by fcavillo** [comment]
> We are going to have to use namespaces for the sockets, which we should have been doing from the start. It allows multiplexing and allows the nginx proxy to work. Basically the chat and game have their own namespace, which allows for SOC (seperation of concerns) is this going to affect your stuff @fcavillo ?

My use of the sockets is just a couple lines so it should not change much for me. As long as @shuyenla and @antrup 's parts still work, mine should too !

**Review by 5atchm1n — APPROVED** [review]
looks great @fcavillo @mvaldes42  :1st_place_medal:

**Comment by mvaldes42** [comment]
> we have some conflicts @fcavillo @mvaldes42 probably because of the previous PR can you fix this ?

yeah, will do !

**Pull request merged**
