### PR TITLE
:rocket: Shlu/update/leader board

### PR DESCRIPTION
**Pull request by shuyenla**
there're 4 new features for leader board
- [x]  link rank and win rate
- [x]  display avatar
- [x]  fix 42 login no display
- [x]  on click link to user profile

there're some commits for chat cause at one point I could't log in with main so I clone my chat update branch to deal with leader board

pls let me know if there's something not yet been taking care off otherwise it's done :smile_cat:

### CODE REVIEW

**Comment by mvaldes42** [comment]
hey, so i have an empty leaderboard for both 42 and email and errors in the front end as well ! Perhaps something changed when you merged ?

**Comment by fcavillo** [comment]
Hey ! Nice work :+1: 

A couple issues : 
- there is a front error even with fresh install, a double import in Auth.tsx ?
- leaderboard page needs to be refreshed to display the leaderboard

A couple non-necessary fixes :)))) : 
- Could it be possible to display something when the leaderboard is empty ? Like 'no winners yet' oor smthg
- Is it possible to set a max number of decimals for the winrate ? Like 0.66 instead of 0.66666666666666666666666666666666666 

Let me know if I missed something !

**Comment by shuyenla** [comment]
> [x] there is a front error even with fresh install, a double import in Auth.tsx ?
> [] leaderboard page needs to be refreshed to display the leaderboard
This is due to when login there's no userId data 
> 
> A couple non-necessary fixes :)))) :
> 
> [] Could it be possible to display something when the leaderboard is empty ? Like 'no winners yet' oor smthg
> [x] Is it possible to set a max number of decimals for the winrate ? Like 0.66 instead of 0.66666666666666666666666666666666666
> 
> Let me know if I missed something !

**Review by fcavillo — APPROVED** [review]
- New empty leaderboard message
- Rounded winrates
- Clickable profiles
- Leaderboard updates after going on another tab, no need to refresh anymore

 Great job :+1:

**Review by mvaldes42 — APPROVED** [review]
Works perfectly for me as well ! Congrats :100:

**Pull request merged**
