### PR TITLE
Toni/front/game/finetuning

### PR DESCRIPTION
**Pull request by antrup**
Add:
- solo mode
- various buttons (play again, cancel ...)
- customization of keyboard controls (up and down)
- avatars in game
Change:
- ball speed (slow at start and speed increase step by step)
Improve:
- watch and game front ends
- various minor improvements

### CODE REVIEW

**Comment by mvaldes42** [comment]
So I just have a few questions/ notes:

- sometimes for some reason, the window is not 100 height and there is a scrollbar to the side, preventing from using the keys up and down arrows to play. Perhaps can you disable scrolling in div in css or prevent keys event from doing default action ?
- the avatars in the watch interfaces don't match user's
Screenshot from 2022-08-21 16-24-19

- _ball speed (slow at start and speed increase step by step_ isn't implemented ? :rocket: 
- what about when someone leave the game window, and wants to go back to the game he left ? Because now it asks if we want to play another game. Or perhaps by design we say we can't leave the window ?
- it takes like so long to fetch avatars of the users in the watch interface :shrug: 

- the div where the ongoing games are shown is weirdly narrow, would be nice to have it 100% width ^^

Screenshot from 2022-08-21 16-32-25

Otherwise
- Game works great :+1: !
- Solo game is a good idea as well, and works !
- New buttons, and interface :100:

**Comment by mvaldes42** [comment]
I got those warnings as well :

- `Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the SoloGame component.
    at SoloGame (http://localhost:3000/static/js/bundle.js:4503:5)
    at div
    at Game (http://localhost:3000/static/js/bundle.js:3252:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:65882:26)
    at main
    at UserInterface
    at RequireAuth (http://localhost:3000/static/js/bundle.js:493:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:65882:26)
    at div
    at App
    at Routes (http://localhost:3000/static/js/bundle.js:65974:5)
    at Router (http://localhost:3000/static/js/bundle.js:65907:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:64716:5)
    at main
    at AuthProvider (http://localhost:3000/static/js/bundle.js:526:5)`

-     `Warning: Game(...): When calling super() in `Game`, make sure to pass up the same props that your component's constructor was passed.
    at Game (http://localhost:3000/static/js/bundle.js:3252:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:65882:26)
    at main
    at UserInterface
    at RequireAuth (http://localhost:3000/static/js/bundle.js:493:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:65882:26)
    at div
    at App
    at Routes (http://localhost:3000/static/js/bundle.js:65974:5)
    at Router (http://localhost:3000/static/js/bundle.js:65907:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:64716:5)
    at main
    at AuthProvider (http://localhost:3000/static/js/bundle.js:526:5)`

- `Warning: Watch(...): When calling super() in `Watch`, make sure to pass up the same props that your component's constructor was passed.
    at Watch (http://localhost:3000/static/js/bundle.js:5313:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:65882:26)
    at main
    at UserInterface
    at RequireAuth (http://localhost:3000/static/js/bundle.js:493:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:65882:26)
    at div
    at App
    at Routes (http://localhost:3000/static/js/bundle.js:65974:5)
    at Router (http://localhost:3000/static/js/bundle.js:65907:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:64716:5)
    at main
    at AuthProvider (http://localhost:3000/static/js/bundle.js:526:5)`

-     `Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Paddle
printWarning @ react-dom.development.js:86
warn @ react-dom.development.js:49
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:12912
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:27310
commitRootImpl @ react-dom.development.js:26702
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
`

**Comment by mvaldes42** [comment]
sidenote, you can have multiple users in localhost, that dont share localStorage, using new profiles in chrome
Screenshot from 2022-08-21 16-50-52

**Comment by antrup** [comment]
Hi @mvaldes42 , thx for your comments!

> * sometimes for some reason, the window is not 100 height and there is a scrollbar to the side, preventing from using the keys up and down arrows to play. Perhaps can you disable scrolling in div in css or prevent keys event from doing default action ?

It seems to be due to the sidebar which is not responsive. So, I prevent default key event as a quick fix.

> * the avatars in the watch interfaces don't match user's

fixed

> * _ball speed (slow at start and speed increase step by step_ isn't implemented ? rocket

it is and it seems to work on my side... still too fast for you? @5atchm1n @fcavillo @shuyenla could you check? I can indeed make the ball even slower if you want.

> * what about when someone leave the game window, and wants to go back to the game he left ? Because now it asks if we want to play another game. Or perhaps by design we say we can't leave the window ?

Confirm, we consider quitting the window as giving up the game. So the opponent automatically win the game.

> * it takes like so long to fetch avatars of the users in the watch interface shrug

I know and I ve already spent way too much time trying to fix this. Even if I force the re-rendering, the page do not update (ie the avatars do not show up), I cannot figure why...
Unless someone want to help fix this, we can either:
- keep things as is
- remove the avatars in the list of ongoing games

> * the div where the ongoing games are shown is weirdly narrow, would be nice to have it 100% width ^^

fixed

**Comment by fcavillo** [comment]
Hey, nice work :) 

I seem to be having a couple issues too : 
- very sad : my arrow keys are not always working depending on the window, but I can't see why ?
- moderately sad : the ball speed does not seem to reinitialize after the end of a game, if I make 5 games with the same player the speed gets extremely high
- slightly sad : the avatars flicker/blink in the first 3 seconds of starting a game

For the avatars not showing in the ongoing games, I think unless someone has time to look at it, we can remove them from the page :)

**Comment by mvaldes42** [comment]
> For the avatars not showing in the ongoing games, I think unless someone has time to look at it, we can remove them from the page :)

I might have a look at the avatars later :)

**Comment by antrup** [comment]
@fcavillo, many thanks for your review!

> * very sad : my arrow keys are not always working depending on the window, but I can't see why ?

I cannot reproduce this issue... could you tell me more about your config (browser ...)?

> * moderately sad : the ball speed does not seem to reinitialize after the end of a game, if I make 5 games with the same player the speed gets extremely high

fixed

> * slightly sad : the avatars flicker/blink in the first 3 seconds of starting a game

fixed

**Comment by fcavillo** [comment]
> I cannot reproduce this issue... could you tell me more about your config (browser ...)?

Well I can't either now so it must have been a bug on my side only.

The ball speed is fixed, thanks !

I still have the flickering of the avatars at the start of a game, maybe my mac is too slow.

**Review by fcavillo — APPROVED** [review]
Nice job,  the bugs are fixed !

**Review by 5atchm1n — APPROVED** [review]
few minor bugs - but we will fix them after

**Pull request merged**
