### PR TITLE
Satch/swagger/main

### PR DESCRIPTION
**Pull request by 5atchm1n**
- Too many conflicts in the previous pull request
- Setup swagger for backend from main branch
- This should do it
- You may want to make clean

### CODE REVIEW

**Comment by mvaldes42** [comment]
hey so :

- i stil have error:
```
 backend   | /app/src/user/user.service.ts:149
backend   | 			throw new ForbiddenException('getUser error : ' + error);
backend   |          ^
backend   | ForbiddenException: getUser error : NotFoundError: No User found
backend   |     at UserService.getUser (/app/src/user/user.service.ts:149:10)
``` and `polling.js:311          GET http://localhost:4000/socket.io/?EIO=4&transport=polling&t=OAmf8Lg net::ERR_EMPTY_RESPONSE`
when I start the project so i have to comment
- when i log in with 42 i get `GET http://localhost:4000/users/me 401 (Unauthorized)`
- i don't have previous issue when logging in with email
- i can't access swagger via http://locahost:4000/api

**Comment by 5atchm1n** [comment]
I feel this issue is coming from the fact the browser is making a call to the users/me when we load the signin page. If I close the browser the error goes away..

**Comment by 5atchm1n** [comment]
> hey so :
> 
> * when i log in with 42 i get `GET http://localhost:4000/users/me 401 (Unauthorized)`
> * i don't have previous issue when logging in with email
> * i can't access swagger via http://locahost:4000/api

I fixed the 42 signin

**Comment by shuyenla** [comment]
when i try to login with 42 i got this 
`{"statusCode":500,"message":"Internal server error"}` :cry: @5atchm1n

**Comment by shuyenla** [comment]
works well after i renewed my 42 secret! good job :+1:

**Review by shuyenla — APPROVED** [review]

**Review by mvaldes42 — APPROVED** [review]
Everything works well :fire: 
So great to have a tool like swagger !

**Pull request merged**
