### PR TITLE
Mvaldes/feature/user private profile

### PR DESCRIPTION
**Pull request by mvaldes42**
i'm asking for a pull request so that we can be on the same page.

I've done :
- changed the routes structure to only authorize the landing page when not logged in
- files structure in the front to keep the concerns separate
- wip for the user profile page (waiting for some back functions to complete)
- now on login, fetch to users/me to get the user info
- keep logging on refresh

What's left to do:

1. complete the user profile friends/ foes
2. fonction for 2FA ?
3. phone number ?
4. get the user email from the back
5. get back confirmation that password is correct when updating user info
6. update avatar function from back
7. On login, add promises to the fetch calls.

### CODE REVIEW

**Comment by shuyenla** [comment]
> ....
> What's left to do:
> 
> 4. get the user email from the back
> 
> ....

Are we not getting the user email by useAuth().user any more ?

**Comment by shuyenla** [comment]
> no, you get the user info with the localStorage so for example, for username, it's `localStorage.getItem("userName")`

Ohhhhh we removed useAuth().user now ? Then there's a lot of stuff I need to change according to that ! I'll deal with it after your merge!

**Comment by mvaldes42** [comment]
> 

mmh the auth context was a way to know if the user was logged in or not. But context does not persist on refresh. So i use both the auth context and local storage to store the context value. You can check if user is logged in with `localStorage!.getItem("userLogged")! === "true"`

**Review by 5atchm1n — APPROVED** [review]
All good from my side !! I love structured projects !!

**Pull request merged**
